export const AUTH_LOGIN = 'auth/LOGIN'
export const AUTH_SIGNUP = 'auth/SIGNUP'
export const AUTH_LOGOUT = 'auth/LOGOUT'
export const AUTH_TOKEN = 'auth/TOKEN'
export const LOGIN_SUCCESS = 'auth/LOGIN/success'
export const LOGIN_FAILURE = 'auth/LOGIN/failure'
export const SIGNUP_SUCCESS = 'auth/SIGNUP/success'
export const SIGNUP_FAILURE = 'auth/SIGNUP/failure'
